# Generated by Django 2.1.3 on 2018-12-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20181211_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profil_picture', models.ImageField(default='static/images/profil_pictures/defaultpicture.jpg', upload_to='static/images/profil_pictures/')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='maillot',
            name='image',
        ),
        migrations.AddField(
            model_name='maillot',
            name='maillot_picture',
            field=models.ImageField(default='static/images/maillot_pictures/maillotdefaut.jpg', upload_to='static/images/maillots_pictures/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/ecran.png', upload_to='static/images/'),
        ),
    ]
