# Generated by Django 2.1.3 on 2018-12-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_auto_20181211_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillot',
            name='maillot_picture',
            field=models.ImageField(default='static/images/maillot_pictures/maillotdefaut.jpg', upload_to='static/images/maillot_pictures/'),
        ),
    ]
